CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  surname VARCHAR NOT NULL,
  email VARCHAR NOT NULL UNIQUE,
  one VARCHAR NOT NULL UNIQUE,
  two VARCHAR NOT NULL UNIQUE,
  three VARCHAR NOT NULL UNIQUE,
  hpassword VARCHAR(100) NOT NULL,
);

CREATE TABLE passwords (
  id SERIAL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  question VARCHAR NOT NULL,
  answer VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
);

CREATE TABLE confirmations (
  id SERIAL PRIMARY KEY,
  email VARCHAR NOT NULL,
  plate VARCHAR NOT NULL,
  amount VARCHAR NOT NULL,
  code VARCHAR NOT NULL,
);

CREATE TABLE money (
  id SERIAL PRIMARY KEY,
  email VARCHAR NOT NULL ,
  balance INTEGER NOT NULL
);
